name: Build and Publish

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4

      - name: Install dependencies
        working-directory: ./client
        run: go mod tidy

      - name: Build Linux binary
        working-directory: ./client
        env:
          API_URL: ${{ secrets.API_URL }}
          VERSION: ${{ github.ref_name }}
          GOOS: linux
          GOARCH: amd64
        run: go build -o dist/wowa-linux64 -ldflags "-X main.version=$VERSION -X main.apiUrl=$API_URL"

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: wowa-linux64
          path: client/dist/wowa-linux64

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4

      - name: Install dependencies
        working-directory: ./client
        run: go mod tidy

      - name: Build Windows binary
        working-directory: ./client
        env:
          API_URL: ${{ secrets.API_URL }}
          VERSION: ${{ github.ref_name }}
          GOOS: windows
          GOARCH: amd64
        run: go build -o dist/wowa-win64.exe -ldflags "-X main.version=$env:VERSION -X main.apiUrl=$env:API_URL"

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: wowa-win64.exe
          path: client/dist/wowa-win64.exe

  publish:
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows]
    steps:
      - name: Download Linux binary
        uses: actions/download-artifact@v4
        with:
          name: wowa-linux64
          path: dist

      - name: Download Windows binary
        uses: actions/download-artifact@v4
        with:
          name: wowa-win64.exe
          path: dist

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/wowa-linux64
            dist/wowa-win64.exe
