name: Build and Publish

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v4

      - name: Install dependencies
        run: go mod tidy

      - name: Build
        env:
          API_URL: ${{ secrets.API_URL }}
          VERSION: ${{ github.event.release.tag_name }}
        run: |
          GOOS=linux GOARCH=amd64 go build -o dist/wowa-linux64 -ldflags "-X main.version=${VERSION} -X main.apiUrl=${API_URL}"
          GOOS=windows GOARCH=amd64 go build -o dist/wowa-win64.exe -ldflags "-X main.version=${VERSION} -X main.apiUrl=${API_URL}"

      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/wowa-linux64
            dist/wowa-win64.exe
